/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.uhh.lt.autolinks.wikiservice.api.handler;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.uhh.lt.autolinks.wikiservice.api.model.Error;
import de.uhh.lt.autolinks.wikiservice.api.model.Query;
import de.uhh.lt.autolinks.wikiservice.api.model.RDFtriple;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-10-20T11:38:12.357+02:00")

@Api(value = "find", description = "the find API")
public interface FindApi {

    @ApiOperation(value = "Search results as triples", notes = "Search a wikipedia index and retrieve results as RDF triples ", response = RDFtriple.class, responseContainer = "List", tags={ "Search", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A list of result triples", response = RDFtriple.class, responseContainer = "List"),
        @ApiResponse(code = 405, message = "Invalid query input", response = Void.class),
        @ApiResponse(code = 200, message = "Unexpected error", response = Error.class) })
    
    @RequestMapping(value = "/find",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<?> findPost(@ApiParam(value = "Forwarded elasticsearch query dsl"  )  @Valid @RequestBody Query query);

}
