/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.uhh.lt.autolinks.wikiservice.api.handler;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.uhh.lt.autolinks.wikiservice.api.model.Error;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-10-20T13:51:53.035+02:00")

@Api(value = "ping", description = "the ping API")
public interface PingApi {

    @ApiOperation(value = "check availability", notes = "returns OK if service is fully available or ERROR if service partly fails ", response = Void.class, tags={ "Admin", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "empty ok message if fully available", response = Void.class),
        @ApiResponse(code = 200, message = "Unexpected error", response = Error.class) })
    
    @RequestMapping(value = "/ping",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> pingGet();

}
