######
##
# 1) start: docker-compose up -d
# 2) attach: docker attach ...
# 3) detach: detach with <CTRL-p> <CTRL-q>
# 4) stop: docker-compose down
##
######
version: '2.3'

networks:
  anet:

services:

  ##
  # Main components and their dependencies
  ##
  # BEGIN: frontend
  frontend:
    image: node:9.2
    volumes:
      - ${PWD}/frontendserver:/opt/project
    ports:
      - 10001:10010
      - 3001:3001
    networks:
      - anet
    stdin_open: true
    tty: true
    working_dir: /opt/project
    entrypoint: bash
    environment:
      - NODE_ENV=development
      - COOKIE_SECRET=YOUR_COOKIE_SECRET
      - LOGLEVEL=debug
  # END: frontend

  # BEGIN: broker
  broker:
    image: remstef/node-swagger:latest
    volumes:
      - ${PWD}/broker:/opt/project/broker
    ports:
      - 10000:10010
      - 3000:3001
    networks:
      - anet
    stdin_open: true
    tty: true
    working_dir: /opt/project/broker
    entrypoint: bash
    environment:
      - NODE_ENV=development
      - COOKIE_SECRET=YOUR_COOKIE_SECRET
      - LOGLEVEL=debug

  brokermysqlserver:
    image: "mysql:5.7"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=autolinks
      - MYSQL_USER=autolinks
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=autolinks
    volumes:
      - ${PWD}/broker-mysql-data:/var/lib/mysql
    command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-pautolinks", "-uautolinks"]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      anet:
        aliases:
          - mysql
  # END: broker

  ##
  # Services and their dependencies
  ##
  # BEGIN: dummy service
  dummy:
    image: remstef/node-swagger:latest
    volumes:
      - ${PWD}/services/dummy:/opt/project/services/dummy
      - ${PWD}/broker:/opt/project/broker
    ports:
      - 10010:10010
      - 3010:3001
    networks:
      - anet
    stdin_open: true
    tty: true
    working_dir: /opt/project/services/dummy
    entrypoint: bash
    environment:
      - NODE_ENV=development
      - COOKIE_SECRET=YOUR_COOKIE_SECRET
  # END: dummy service

  # BEGIN: wikiservice
  wiki:
    image: remstef/node-swagger:latest
    volumes:
      - ${PWD}/services/wikiservice/wikiservice-node:/opt/project/services/wikiservice/wikiservice-node
      - ${PWD}/broker:/opt/project/broker
    ports:
      - 10011:10010
      - 3011:3001
    networks:
      - anet
    stdin_open: true
    tty: true
    working_dir: /opt/project/services/wikiservice/wikiservice-node
    entrypoint: bash
    environment:
      - NODE_ENV=development
      - LOGLEVEL=debug
      - COOKIE_SECRET=YOUR_COOKIE_SECRET
      - ELASTICSEARCH_URLS=http://elasticsearch:9200
      - ELASTICSEARCH_INDICES=simplewiki
#      - ELASTICSEARCH_URLS=http://ltdocker.informatik.uni-hamburg.de:10004
#      - ELASTICSEARCH_INDICES=enwiki,wikidata,enwiktionary

  es:
    image: custom-elasticsearch:5.5.2
    build:
      context: services/wikiservice/es
      dockerfile: Dockerfile
#      args:
#        CUSTOM_UID: 39000
#        CUSTOM_GID: 390
    environment:
      - cluster.name=escluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 131072
        hard: 131072
      nproc:
        soft: 8192
        hard: 8192
    cap_add:
      - IPC_LOCK
    volumes:
      - ${PWD}/services/wikiservice/esdata:/usr/share/elasticsearch/data
      #- ${PWD}/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      anet:
        aliases:
          - elasticsearch
    healthcheck:
      test: curl --silent --fail 'localhost:9200/_cluster/health' || exit 1
      interval: 5s
      timeout: 2s
      retries: 12

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - anet
    depends_on:
      elasticsearch:
        condition: service_healthy
  # END: wikiservice
