swagger: '2.0'
info:
  version: '0.0.1'
  title: Autolinks NLP Service

consumes:
  - application/json
produces:
  - application/json

# define complex objects which can be references with $ref: "#/definitions/X"
definitions:

  Document:
    type: object
    properties:
      text:
        type: string
      source:
        type: string
      language:
        type: string

  NamedEntity:
    type: object
    properties:
      text:
        type: string
      type:
        type: string
      offset:
        $ref: "#/definitions/Offset"
      analyzer:
        type: string

  Offset:
    type: object
    properties:
      from:
        type: integer
      to:
        type: integer

  Error:
    type: object
    properties:
      message:
        type: string
      fields:
        type: string

tags:
  - name: NLP
    description: Everything about nlp

paths:
  /findentities:
    x-swagger-router-controller: nlp
    post:
      operationId: find_named_entities
      tags:
        - NLP
      description: Find named entites in the provided text
      parameters:
        - name: document
          in: body
          description: |
            The document object which contains the plain text and some
            configuration parameters, e.g. the desired language of analyis.
          schema:
            $ref: "#/definitions/Document"
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/NamedEntity"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

  /swagger:
    x-swagger-pipe: swagger_raw
