swagger: '2.0'
info:
  version: '0.0.1'
  title: Autolinks Broker Service

# the domain of the service
host: 127.0.0.1:10010

# array of all schemes that the API supports
schemes:
  # - https
  - http

# will be prefixed to all paths (comment for no prefix)
basePath: /

# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

# define complex objects which can be references with $ref: "#/definitions/X"
definitions:

  Service:
    type: object
    properties:
      name:
        type: string
        description: the name of the service
      location:
        type: string
        description: where to find the service
      description:
        type: string
        description: summray fo the service
      endpoints:
        type: array
        description: the endpoints a service offers
        items:
          $ref: '#/definitions/Endpoint'

  Endpoint:
    type: object
    properties:
      name:
        type: string
        description: the name of the endpoint
      servicename:
        type: string
        description: the name of the service
      requireslogin:
        type: boolean
        description: does the service require a user to be logged in?

  Error:
    type: object
    properties:
      message:
        type: string
      fields:
        type: string

tags:
  - name: Service
    description: Everything about connected services

paths:
  /registerService:
    # tell nodejs where to find the code for this path
    x-swagger-router-controller: services
    post:
      tags:
        - Service
      description: Register a service
      # used as the method name of the controller
      operationId: register_service
      parameters:
        - name: service
          in: body
          description: The service which wants to be added
          schema:
            $ref: "#/definitions/Service"
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

  /listServices:
    x-swagger-router-controller: services
    get:
      tags:
        - Service
      description: List registered services
      # used as the method name of the controller
      operationId: list_services
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Service"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

  /pingServices:
    x-swagger-router-controller: services
    get:
      tags:
        - Service
      description: Ping registered services
      # used as the method name of the controller
      operationId: ping_services
      responses:
        200:
          description: Success
        default:
          description: Error

  /pingService:
    x-swagger-router-controller: services
    post:
      tags:
        - Service
      description: Ping registered service
      # used as the method name of the controller
      operationId: ping_service
      parameters:
        - name: service
          in: body
          description: The name of the of the service to ping
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        200:
          description: Success
        default:
          description: Error


  /swagger:
    x-swagger-pipe: swagger_raw
