######
##
# 1) start: docker-compose up -d
# 2) attach: docker attach nlpservicedev
# 3) detach: detach with <CTRL-p> <CTRL-q>
# 4) stop: docker-compose down
##
######
version: '2.3'

networks:
  anet:

services:
  frontendserver:
    image: node:9.2
    container_name: nlpservicedev
    volumes:
      - ${PWD}:/opt/project
    ports:
      - 10010:10010
      - 3001:3001
    networks:
      - anet
    stdin_open: true
    tty: true
    working_dir: /opt/project
    entrypoint: bash
    environment:
      - NODE_ENV=development
      - COOKIE_SECRET=YOUR_COOKIE_SECRET
      - LOGLEVEL=debug
