##
#
# API description of wikipedia service
#
# ---
# dev note: edit with https://editor.swagger.io//#/ to check validity
# ---
##

swagger: '2.0'

info:
  version: '0.0.1'
  title: Autolinks Wikipedia Service Connector API
  description: Lorem Ipsum
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# the domain of the service
host: SERVER_URL

# array of all schemes that the API supports
schemes:
  - https
  - http

# will be prefixed to all paths (comment for no prefix)
basePath: /

definitions:

  Service:
    type: object
    properties:
      name:
        type: string
        description: the name of the service
      location:
        type: string
        description: where to find the service
      description:
        type: string
        description: summray fo the service
      endpoints:
        type: array
        description: the endpoints a service offers
        items:
          $ref: '#/definitions/Endpoint'
          
  Endpoint:
    type: object
    properties:
      name: 
        type: string
        description: the name of the endpoint
      servicename:
        type: string
        description: the name of the service
      requireslogin:
        type: boolean
        description: does the service require a user to be logged in?

  RDFtriple:
    type: object
    properties:
      subject:
        type: string
        description: the subject of the rdf triple
      predicate:
        type: string
        description: the predicate of the the rdf triple
      object:
        type: string
        description: the object of the rdf triple
      properties:
        type: array
        description: additional properties are also rdf triples
        items:
          $ref: '#/definitions/RDFtriple'

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
      cause:
        type: object

# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

tags:
  - name: Search
    description: Everything about your search
  - name: Admin
    description: Everything about the administration of the service

paths:
  /ping:
    get:
      tags:
        - Admin
      summary: check availability
      description: |
        returns OK if service is fully available or ERROR if service partly fails
      consumes: []
      parameters: []
      responses:
        200:
          description: empty ok message if fully available
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /registerAtBroker:
    post:
      tags:
        - Admin
      summary: manually register this service and its endpoints at autolinks broker service
      description: |
        returns OK if service was registered
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: broker
          description: object holding the location
          schema:
            type: object
            properties:
              location:
                description: where to find the broker
                type: string
                default: { "location": "http://BROKER_SERVER:BROKER_PORT/BROKER_BASE_PATH" }
      responses:
        200:
          description: empty ok message if registered
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /find:
    post:
      tags:
        - Search
      summary: Search results as triples
      description: |
        Search a wikipedia index and retrieve results as RDF triples
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: query
          description: Forwarded elasticsearch query dsl
          schema:
            type: object
            properties:
              wiki:
                description: |
                  Which wiki to use:
                    - enwiki
                    - simplewiki
                    - wikidata
                    - enwiktionary
                  default: *
                type: array
                items:
                  type: string
              query:
                type: object
                default: { "query": { "match_all": { } } }
      responses:
        200:
          description: A list of result triples
          schema:
            type: array
            items:
              $ref: '#/definitions/RDFtriple'
        405:
          description: "Invalid query input"
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
