
##
# 1) start: docker-compose up -d
# 2) attach: docker attach autolinksbrokerdev
# 3) detach: detach with <CTRL-p> <CTRL-q>
# 4) stop: docker-compose down
##
version: '2.3'

networks:
  alnet:

services:
  frontendserver:
    image: node:8.7.0
    container_name: autolinksbrokerdev
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - 10010:10010
      - 3001:3001
    networks:
      - alnet
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    entrypoint: bash
    environment:
      - NODE_ENV=development
      - COOKIE_SECRET=YOUR_COOKIE_SECRET
    mem_limit: 1g
    memswap_limit: 1g
