##
# see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
##
version: '2.3'

networks:
  esnet:

services:
  esmaster:
    image: custom-elasticsearch:5.5.2
    build:
      context: es
      dockerfile: Dockerfile
#      args:
#        CUSTOM_UID: 39000
#        CUSTOM_GID: 390
    environment:
      - cluster.name=escluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      # - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 131072
        hard: 131072
      nproc:
        soft: 8192
        hard: 8192
    # mem_limit: 1372m
    # memswap_limit: 1372m
    # mem_swappiness: 0
    cap_add:
      - IPC_LOCK
    volumes:
      - ${PWD}/esdata:/usr/share/elasticsearch/data
      #- ${PWD}/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      esnet:
        aliases:
          - elasticsearch
    healthcheck:
      test: curl --silent --fail 'localhost:9200/_cluster/health' || exit 1
      interval: 5s
      timeout: 2s
      retries: 12

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      esmaster:
        condition: service_healthy
